### ISSUE TITLE
Consider adding functional tests to this project

### ISSUE THREAD

**Issue by danielbachhuber** [JayWood/jw-wpcli-random-posts#1]
Functional tests are an integral ingredient of highly-quality, maintainable commands. WP-CLI tries to make it as easy as possible to add functional tests to your package with its `wp scaffold package-tests` command:

https://github.com/wp-cli/scaffold-package-command#wp-scaffold-package-tests

I'd encourage you to consider adding functional tests to your package :) By starting your functional tests early on, it also makes it much easier to maintain your project over time.

**Comment by JayWood** [comment]
@danielbachhuber it's been awhile since I looked at this project, but I just pushed an update so wanted to checkout issues.

I have plans to implement tests at some point, just not ETA on that since the script itself is quite small.
