### ISSUE TITLE
Docker and featured images.

### ISSUE THREAD

**Issue by slawekniewiadomski** [JayWood/jw-wpcli-random-posts#12]
Aloha,
I came across weird behavior. 
On my dev setup i run docker with wp and wp-cli + your ubercool script and i love it.
When i try  to generate posts with feature images, script dies here, resulting with one post WITHOUT featured image. 
![zrzut ekranu z 2017-09-27 00-26-15](https://user-images.githubusercontent.com/14282736/30887391-8a3327aa-a31b-11e7-89b6-157c670590eb.png)
Ends the same when running attached to container

Also, --img-type seems mandatory, even if not generating featured images.

Tested 1.2, 1.3, and dev-master, on various containers. Same result, any ideas?

**Comment by JayWood** [comment]
This was due to a default set and there still seems to be a bug in WPCLI when using defaults. I've fixed this in the latest release, closing.
