### ISSUE TITLE
There is not generate subcommand.

### ISSUE THREAD

**Issue by nextgenthemes** [JayWood/jw-wpcli-random-posts#13]
It points me to help and that shows only posts and some other command, trail and errored past then to get a error about taxonomy none or empty ... ended up with a random posts with the posts subcommand eventually.

**Comment by JayWood** [comment]
Yea, same issue, just pushed an update that fixes the taxonomy failure - https://github.com/JayWood/jw-wpcli-random-posts/releases/tag/1.3

There was another issue if you're like me and your install doesn't have php_exif enabled. But, that was just tested and tagged fixed in 1.3
