### ISSUE TITLE
Ability to remove random generated data later

### ISSUE THREAD

**Issue by colorful-tones** [JayWood/jw-wpcli-random-posts#3]
It would be awesomesauce if there was an ability to remove the randomly generated data with a secondary command later. 

I know you mentioned possibly using a meta key.

Feature request! Feature request! PLEASE?!?!?!?!? :-D

**Comment by JayWood** [comment]
Will slate this for the weekend, have the perfect idea in mind.
1. Store a meta key against every generated post, attachment, AND term ( since we can now store term meta )
2. Create a secondary command to 'cleanup' items by this meta key.

**Comment by JayWood** [comment]
@colorful-tones here ya go buddy!!!
