### ISSUE TITLE
Img-type paramater is required

### ISSUE THREAD

**Issue by bradp** [JayWood/jw-wpcli-random-posts#9]
Even if I don't care about images, I need to define this flag.

**Comment by JayWood** [comment]
@bradp I can't find the error message we seen during the screen share, wondering if you were on an older version?

**Comment by colorful-tones** [comment]
I can verify this is still happening. Steps to reproduce:

1. `wp package install jaywood/jw-wpcli-random-posts:dev-master`
2. `wp jw-random generate 10`

I get back:
```
Error: Parameter errors:
 Invalid value specified for 'img-type' (Sets the image provider)
```

Running WP-CLI 1.4.1.

**Comment by andreasciamanna** [comment]
Just installed (from master), tested `wp jw-random generate 10 --featured-image --tax=category,post_tag --tax-n=15` and got the same error:

```
Error: Parameter errors:
 Invalid value specified for 'img-type' (Sets the image provider)
```

**Comment by andreasciamanna** [comment]
Specifying the argument to "business" or "random" causes the same error.
Using "abstract" I managed to get rid of that error.

It looks like the possible values, as well as the default one used by this package, does not match whe ones available in lorempixel.com.

However, I get a bunch of other errors I'm going to report in a separate issue.

**Comment by JayWood** [comment]
Closing as resolved with latest release. Also, haven't heard from you in awhile @bradp hope you're doing well 😄
